### ISSUE TITLE
deleting the most recent item on the server causes hang

### ISSUE THREAD

**Issue by taki-fugu** [JakeWharton/docker-gphotos-sync#26]
Following a successful sync, if the most recent item is deleted from Google Photos, the next sync hangs indefinitely after "Marking https://photos.google.com/photo/xxxxxxxxxxxxxx" without timing out (xxxxxxxxxxxxxx is the deleted item).
Uploading more items hence creating a new most recent item in the feed won't fix the problem. Only restoring the deleted item from the trash enables successful completion.
Looks like if the program can't find the last item it synced in the previous iteration on the server, it just hangs.

**Comment by JakeWharton** [comment]
Can you file this on the http://github.com/perkeep/gphotos-cdp project? This repo is just a Docker container which wraps that tool.

**Comment by taki-fugu** [comment]
done

**Comment by JakeWharton** [comment]
Thanks!

(https://github.com/perkeep/gphotos-cdp/issues/17 for anyone following along)
