### ISSUE TITLE
Allow custom healthcheck URL

### ISSUE THREAD

**Issue by karan** [JakeWharton/docker-gphotos-sync#29]
I use a self-hosted HC instance and would like to use that for monitoring gphotos-sync.

It'll be more flexible if HEALTHCHECK_ID was instead HEALTHCHECK_URL.

**Comment by JakeWharton** [comment]
It used to be URL but then it felt weird to just append `/start` and hope it would work. Since this isn't common, I would prefer to add `HEALTHCHECK_HOST` where you can specify a host and port. Is that enough for you?

I was actually talking to someone else about this last week...

**Comment by karan** [comment]
Yeah that would work as an override (though I personally find the whole URL as more flexible).

**Comment by JakeWharton** [comment]
We could allow specifying two full URLs then, at the expense of you having to specify the full /start URL and the regular one. This would also make it agnostic to the provider of the health check since presumably there are other services which do similar things, although you have no way of controlling the body or headers of the requests.

**Comment by karan** [comment]
That'd be fine although a bit too verbose. A couple of other options:

* Keep 1 URL, assume that URL the URL is a HC URL and follows their spec. `/start` and all.
* Keep 1 URL, and a `IS_HEALTHCHECK_API` bool. That being `true` would make it so we can use the `/start` API.

**Comment by issmirnov** [comment]
+1 to `HEALTHCHECK_HOST`. I was about to open a PR when I saw this issue.

**Comment by issmirnov** [comment]
Thank you! Confirmed working.

Note to other passing users: reminder that unless you have a redirect setup on a root domain, you probably want to set `https://your.domain.com/ping` as the healthcheck host, not just `https://your.domain.com`
