### ISSUE TITLE
Don't run if process already running

### ISSUE THREAD

**Issue by karan** [JakeWharton/docker-gphotos-sync#30]
Something like this:

```
    if pidof -x gphotos-cdp >/dev/null; then
        echo "already running"
        exit
    fi
```

**Comment by JakeWharton** [comment]
This should already be handled by `flock`:

https://github.com/JakeWharton/docker-gphotos-sync/blob/a2b56f39307db9ad0e9e3720aec950d8e2709a5f/root/etc/cont-init.d/20-cron.sh#L35

Are you sure you're seeing concurrent runs? With what container version?

**Comment by karan** [comment]
I don't believe I saw it in the container but I didn't see any safeguards for it. If flock handles it then this can be closed.
