### ISSUE TITLE
Hang process workaround - timeout

### ISSUE THREAD

**Issue by karan** [JakeWharton/docker-gphotos-sync#31]
So I just noticed that the container was hung for me for the last 2 days. A workaround I figured is to set a timeout on the container itself:

```
# on my ubuntu server
$ timeout 3h docker run --name gphotos-sync --rm -v ...
```

This basically kills the container after 3h and my crontab carries on the next time it ticks. Thought it was worth sharing here.

**Comment by JakeWharton** [comment]
Thanks the hangs are tracked by #20. Doing something like that only works for non-compose usage, unfortunately.
