### ISSUE TITLE
fix_time.sh fails for PNGs and halts the backup

### ISSUE THREAD

**Issue by aviramsegal** [JakeWharton/docker-gphotos-sync#33]
This seems to be happening for screenshots I got in my photo library.

2020/10/18 08:28:55 Running /app/fix_time.sh on /download/AF1QipNs0cGskrFJsoxUW-X65C777zLQ3Gmp0O4VXFC2/Screenshot_20201017-215132.png
Unable to set file mtime. Unsupported file extension: png

**Comment by JakeWharton** [comment]
The script failing should not prevent the backup from continuing. I see tons of failures in my logs and it continuing on to the next image.

**Comment by aviramsegal** [comment]
Guess its something else then, I'll continue debugging
