### ISSUE TITLE
Container does nothing?

### ISSUE THREAD

**Issue by coolspot18** [JakeWharton/docker-gphotos-sync#36]
Hello,

I've configured the container in Synology including setting up dorowu/ubuntu-desktop-lxde-vnc to log into photos.google.com and save the username/password to /config.

However, when I launch gphoto-sync, nothing seems to happen? The last log I see is [services.d] done... and it just sits there?

![Jake](https://user-images.githubusercontent.com/5160442/98597262-bdd99180-22a6-11eb-908b-adc757d0fc7d.PNG)

**Comment by JakeWharton** [comment]
What cron specifier are you using?

**Comment by coolspot18** [comment]
Hello @JakeWharton,

I left it blank - i.e. no Cron. Should I remove the environment variable entirely? 

I just want ot get the initial run up and running to test it out before I set a Cron.

**Comment by coolspot18** [comment]
OK - I've changedf it to the default CRON and it is now running.

In the download photos, photos are grouped in seemingly random folder names - is that to be expected?

**Comment by JackPo** [comment]
The command : chromium-browser --user-data-dir=/path/to/config https://photos.google.com no longer works.  The ubuntu has chrome-browser directly.  Have to change 

"chromium-browser" to "google-chrome"

**Comment by JakeWharton** [comment]
If you do not specify a CRON variable the container will indeed to nothing by default. You would have to trigger the binary manually by specifying it on the command-line (as in https://github.com/JakeWharton/docker-gphotos-sync#initial-sync). It is only when you specify a CRON does it run the tool automatically.

The folder structure is imposed by the upstream tool, but generally yes that is how it looks. If you are consuming the backups into another tool it should be able to use the metadata inside the images to order based on time and location.

**Comment by coolspot18** [comment]
Thanks! 

The container successfully backed up my gphotos, thanks!
