### ISSUE TITLE
Chromium browser missing in  dorowu/ubuntu-desktop-lxde-vnc

### ISSUE THREAD

**Issue by issmirnov** [JakeWharton/docker-gphotos-sync#41]
I'm debugging some auth issues (related to issue 25), and was trying to use the VNC image:

```
docker run -p 6080:80 \
    -v /path/to/config:/config \
    dorowu/ubuntu-desktop-lxde-vnc
```

However, it appears that `chromium-browser` is missing. The README should be updated with an install command.

**Comment by janstadt** [comment]
Try `google-chrome` instead. https://github.com/JakeWharton/docker-gphotos-sync/issues/32#issuecomment-720654309

**Comment by skhaz** [comment]
You need to run `google-chrome --no-sandbox --user-data-dir=/config --no-sandbox https://photos.google.com`
