### ISSUE TITLE
No ARM Docker builds

### ISSUE THREAD

**Issue by chrisbanes** [JakeWharton/docker-gphotos-sync#44]
Any chance we can have an arm64 build?

**Comment by JakeWharton** [comment]
No guarantees it works since I can't test it. Let me know how it goes and I can tag it.

**Comment by JakeWharton** [comment]
Use `jakewharton/gphotos-sync:trunk` to test

**Comment by chrisbanes** [comment]
Thanks! I'll give it a try on my RPi4 soon and report back
