### ISSUE TITLE
authentication not possible in -headless mode

### ISSUE THREAD

**Issue by andyseubert** [JakeWharton/docker-gphotos-sync#52]
Is this project dead now? I haven't seen any response to my issue requests.

I'm now receiving the error in the title . I have re-authenticated several times (perhaps I need to update chrome in that container)

INFO: Starting sync.sh PID 252 Tue Apr 12 00:29:11 UTC 2022
2022/04/12 00:29:12 Session Dir: /tmp/gphotos-cdp
2022/04/12 00:29:12 pre-navigate
2022/04/12 00:29:22 authentication not possible in -headless mode

any ideas?

**Comment by JakeWharton** [comment]
The container is running fine for me locally still so it's alive insofar as it's working for me.

Keep in mind the project being open source and free doesn't mean free or guaranteed support.

This problem is tracked by #25.

**Comment by andyseubert** [comment]
thanks! I'll go look at that issue
