### ISSUE TITLE
x86_64 machine portainer can't run

### ISSUE THREAD

**Issue by JakubKasone** [JakeWharton/docker-gphotos-sync#58]
Hi to everyone,

my name is Jakub and I am self-educating person in this kind of topics (docker, portainer and github now heh)

I am trying run docker-gphotos-sync on my x86_64 desktop. My setup is:

OS: Debian GNU/Linux 11 (bullseye) x86_64 
Host: B85M-HD3 
Kernel: 6.1.0-0.deb11.17-amd64 
Shell: bash 5.1.4 
Terminal: /dev/pts/0 
CPU: Intel Pentium G3240 (2) @ 3.100GHz 
GPU: Intel HD Graphics 
Memory: 1229MiB / 7774MiB

And I followed your setup guide but container log said this:

[cont-init.d] 20-cron.sh: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
INFO: Starting sync.sh PID 213 Sun Apr 21 11:05:00 CEST 2024
2024/04/21 11:05:01 Session Dir: /tmp/gphotos-cdp
2024/04/21 11:05:01 chrome failed to start:
Error relocating /usr/lib/libnspr4.so: gettid: symbol not found

Please, can anyone help me? Thank you.

**Comment by JakeWharton** [comment]
Not sure what the problem is, but this is tracked by #48
